"""Abstract execution plane for sandboxes (Docker ``ContainerManager`` today)."""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, runtime_checkable

from .container_manager import ContainerConfig


@runtime_checkable
class SandboxExecutionPlane(Protocol):
    """Operations the API needs against an isolated environment (container or microVM)."""

    def get_backend_kind(self) -> str: ...
    def check_docker(self) -> bool: ...
    def create_container(self, name: str, config: ContainerConfig) -> Optional[str]: ...
    def run_command(
        self,
        container_id: str,
        command: str,
        cwd: Optional[str] = None,
        env: Optional[Dict[str, str]] = None,
        timeout: Optional[float] = None,
        user: Optional[str] = None,
    ) -> Dict[str, Any]: ...
    def read_file(self, container_id: str, path: str) -> Optional[str]: ...
    def write_file(self, container_id: str, path: str, content: str) -> bool: ...
    def list_files(self, container_id: str, path: str = "/") -> Optional[list]: ...
    def delete_file(self, container_id: str, path: str, recursive: bool = False) -> bool: ...
    def create_directory(self, container_id: str, path: str, mode: int = 0o755) -> bool: ...
    def get_container_stats(self, container_id: str) -> Optional[Dict[str, Any]]: ...
    def kill_container(self, container_id: str, force: bool = True) -> bool: ...
    def is_container_running(self, container_id: str) -> bool: ...
    def pause_instance(self, instance_id: str) -> bool: ...
    def resume_instance(self, instance_id: str) -> bool: ...
